package com.example.fido2.domain.model;

import java.util.Arrays;
import java.util.Base64;
import java.util.Objects;

/**
 * Value object wrapping the raw credential ID byte array.
 *
 * <p>The credential ID is generated by the authenticator during registration and is
 * used to look up the stored credential during authentication.
 */
public final class CredentialId {

    private final byte[] value;

    public CredentialId(byte[] value) {
        Objects.requireNonNull(value, "CredentialId value must not be null");
        this.value = Arrays.copyOf(value, value.length);
    }

    public byte[] getValue() {
        return Arrays.copyOf(value, value.length);
    }

    /** Returns the base64url-encoded string representation (no padding). */
    public String toBase64Url() {
        return Base64.getUrlEncoder().withoutPadding().encodeToString(value);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CredentialId)) return false;
        return Arrays.equals(value, ((CredentialId) o).value);
    }

    @Override
    public int hashCode() {
        return Arrays.hashCode(value);
    }

    @Override
    public String toString() {
        return "CredentialId[" + toBase64Url() + "]";
    }
}
